[gw]
srv-gw ansible_host=192.168.56.1

[ops]
srv-ops ansible_host=192.168.56.10

[web]
srv-web ansible_host=192.168.56.11

[db]
srv-db ansible_host=192.168.56.12
srv-db2 ansible_host=192.168.56.13

[monitor]
srv-monitor ansible_host=192.168.56.14

[backup]
srv-backup ansible_host=192.168.56.15

[all:vars]
ansible_user=abde
ansible_ssh_private_key_file=~/.ssh/id_ed25519
